version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: likemongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  redis:
    image: redis:7.0
    container_name: likeredis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru"]
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M

volumes:
  mongo-data:
  redis-data:
